# Generated by Django 5.2 on 2025-05-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.CharField(blank=True, choices=[('tour', 'Tour'), ('activity', 'Activity')], max_length=20, null=True),
        ),
    ]
