# Generated by Django 5.2 on 2025-05-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.CharField(choices=[('tour', 'Tour'), ('activity', 'Activity')], max_length=20),
        ),
    ]
