# Generated by Django 5.2 on 2025-05-16 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_package_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='package',
            name='date_start',
        ),
    ]
