# Generated by Django 5.2 on 2025-05-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_remove_package_date_end_remove_package_date_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='tour_type',
            new_name='package_type',
        ),
    ]
