# Generated by Django 5.2 on 2025-05-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_exclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
