# Generated by Django 5.2 on 2025-05-31 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0012_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Enquiry', to='packages.package'),
            preserve_default=False,
        ),
    ]
