# Generated by Django 5.2 on 2025-06-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0014_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adults',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='infants',
            field=models.IntegerField(default=0),
        ),
    ]
