# Generated by Django 5.2 on 2025-06-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0015_booking_adults_booking_children_booking_infants'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/'),
        ),
    ]
