# Generated by Django 5.2 on 2025-06-02 11:27

import django.db.models.deletion
import packages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0016_package_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=packages.models.package_image_upload_path),
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='packages/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='packages.package')),
            ],
        ),
    ]
