# Generated by Django 5.2 on 2025-06-02 11:58

import packages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0017_alter_package_featured_image_imagegallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=models.ImageField(upload_to=packages.models.image_gallery_upload_path),
        ),
    ]
