# Generated by Django 5.2 on 2025-06-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0018_package_video_alter_imagegallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
