# Generated by Django 5.2 on 2025-06-02 14:38

import packages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0019_itinerary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=packages.models.image_itinerary_upload_path),
        ),
    ]
