# Generated by Django 5.2 on 2025-06-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0020_alter_itinerary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='map_embed_code',
            field=models.TextField(blank=True, help_text='Paste the full Google Maps iframe embed code here'),
        ),
    ]
