# Generated by Django 5.2 on 2025-06-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0021_package_map_embed_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='group_size',
            new_name='group_size_max',
        ),
        migrations.AddField(
            model_name='package',
            name='group_size_min',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
