# Generated by Django 5.2 on 2025-05-29 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_author_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='social_youtube',
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='blogs.author'),
        ),
    ]
