# Generated by Django 5.2 on 2025-05-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blog_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomponent',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='postcomponent',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postcomponent',
            name='section_type',
            field=models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('single_image', 'Single Image'), ('image_gallery', 'Image Gallery')], max_length=20),
        ),
    ]
