# Generated by Django 5.2 on 2025-05-30 09:15

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_postcomponent_options_postcomponent_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomponent',
            name='single_image',
            field=models.ImageField(blank=True, null=True, upload_to=blogs.models.image_upload_to),
        ),
        migrations.AlterField(
            model_name='postcomponent',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postcomponent',
            name='paragraph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
