# Generated by Django 5.2 on 2025-05-30 09:26

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_postcomponent_single_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=blogs.models.image_upload_to),
        ),
    ]
