# Generated by Django 5.2 on 2025-05-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_subtitle', models.TextField()),
                ('featured_tours_title', models.CharField(max_length=255)),
                ('featured_tours_subtitle', models.TextField()),
                ('featured_activities_title', models.CharField(max_length=255)),
                ('featured_activities_subtitle', models.TextField()),
                ('blog_section_title', models.CharField(max_length=255)),
                ('blog_section_subtitle', models.TextField()),
                ('testimonial_title', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
