# Generated by Django 5.2 on 2025-05-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image_title', models.CharField(max_length=255)),
                ('about_us_title', models.TextField()),
                ('about_us_description', models.TextField()),
                ('company_statistics_title', models.CharField(max_length=255)),
                ('testimonial_title', models.CharField(max_length=255)),
                ('testimonial_description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
