# Generated by Django 5.2 on 2025-05-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutuscontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuscontent',
            name='team_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aboutuscontent',
            name='about_us_title',
            field=models.CharField(max_length=255),
        ),
    ]
