# Generated by Django 5.2 on 2025-05-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_aboutuscontent_team_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuscontent',
            name='team_title',
            field=models.CharField(max_length=255),
        ),
    ]
