# Generated by Django 5.2 on 2025-05-25 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_brandnarrative'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonials',
            new_name='Testimonial',
        ),
    ]
