# Generated by Django 5.2 on 2025-05-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_testimonials_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandnarrative',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
