# Generated by Django 5.2 on 2025-06-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
