# Generated by Django 5.2 on 2025-06-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_testimonial_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
