# Generated by Django 5.2 on 2025-06-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_homepagecontent_hero_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreadImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tours_bread_image', models.ImageField(blank=True, null=True, upload_to='bread-images')),
                ('activities_bread_image', models.ImageField(blank=True, null=True, upload_to='bread-images')),
                ('blogs_bread_image', models.ImageField(blank=True, null=True, upload_to='bread-images')),
                ('about_us_bread_image', models.ImageField(blank=True, null=True, upload_to='bread-images')),
                ('contact_us_bread_image', models.ImageField(blank=True, null=True, upload_to='bread-images')),
            ],
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage-contents/'),
        ),
    ]
