# Generated by Django 5.2 on 2025-06-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_breadimages_alter_homepagecontent_hero_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breadimages',
            options={'verbose_name': 'Breadcrumb Images', 'verbose_name_plural': 'Breadcrumb Images'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='currency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
