# Generated by Django 5.2 on 2025-06-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_miscellaneous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscellaneous',
            name='footer_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
